### ISSUE TITLE
Contacts do not show up on Windows Phone 8.1 client since update to Owncloud 8.1

### ISSUE THREAD

**Issue by ConiKost** [owncloud/contacts#998]
After updating to ownCloud 8.1 and contacts 0.4.0.0 I am unable to sync my contacts with my Lumia 930 (Windows Phone 8.1) anymore. No sync errors are shown.

I can clearly reproduce it, when downgrading to ownCloud 8.0.4 and contacts 0.3.0.19, the sync works again and contacts are being synced without any problems. Switching back to OC 8.1 and the contacts are gone after a sync.

### Steps to reproduce
1. Update ownCloud to 8.1
2. Sync contacts on Windows Phone 8.1
3. Check contacts

### Expected behaviour
All synced contacts are beeing shown

### Actual behaviour
All contacts are missing

### Server configuration
**Operating system**:
Gentoo Linux

**Web server:**
Nginx 1.9.3

**Database:**
MySQL 5.6.25

**PHP version:**
5.6.11

**ownCloud version:**
8.1

**Updated from an older ownCloud or fresh install:**
Update from 8.0.4

**List of activated apps:**
Enabled:
 - bookmarks: 0.4
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - files: 1.1.9
 - files_locking:
 - files_sharing: 0.6.2
 - files_trashbin: 0.6.3
 - tasks: 0.7.1
 - updater: 0.6
Disabled:
 - activity
 - encryption
 - external
 - files_external
 - files_pdfviewer
 - files_texteditor
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - gallery
 - provisioning_api
 - templateeditor
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' =>
  array (
    0 => 'cloud.xxx.de',
  ),
  'datadirectory' => '/var/lib/owncloud',
  'overwrite.cli.url' => 'https://cloud.xxx.de',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'xxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'logtimezone' => 'UTC',
  'installed' => true,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Internet Explorer 11

**Operating system:**
Windows Phone 8.1

#### Web server error log
[21/Jul/2015:00:31:51 +0200] "PROPFIND /remote.php/carddav/principals/xxx/ HTTP/1.1" 207 1233 "-" "MSFT-WP/8.10.14219 (gzip)" "-"
[21/Jul/2015:00:31:51 +0200] "PROPFIND /remote.php/caldav/principals/xxx/ HTTP/1.1" 207 1279 "-" "MSFT-WP/8.10.14219 (gzip)" "-"
[21/Jul/2015:00:31:51 +0200] "PROPFIND /remote.php/carddav/addressbooks/xxx/ HTTP/1.1" 207 2105 "-" "MSFT-WP/8.10.14219 (gzip)" "-"
[21/Jul/2015:00:31:51 +0200] "PROPFIND /remote.php/caldav/calendars/xxx/ HTTP/1.1" 207 3044 "-" "MSFT-WP/8.10.14219 (gzip)" "-"

#### ownCloud log (data/owncloud.log)
none

#### Browser log
none

**Comment by gvde** [comment]
Enable debug logging
https://doc.owncloud.org/server/8.1/developer_manual/general/debugging.html#debug-mode 
Your owncloud log should then contain more information about the requests made...

**Comment by ConiKost** [comment]
It seems, that I can't enable debug? I've added at the bottom define( "DEBUG", 1); to my config.php. But the owncloud.log stays empty and no new entries are beeing added, when syncing contacts.

Any ideas, what I could do wrong?

I've also applied as a test #987 but it didn't help.

At least I think, that the problem has nothing to do with the uuid. Currently none contacts are beeing shown on my windows phone. When I add a new contact, that one is beeing synced, but shown wrong as ";test;;;"

**Comment by gvde** [comment]
Are you sure you look at the right place for the log file? According to your config it should be in /var/lib/owncloud. Is the directory writable? Is the file writable? There should be messages in the log even before you switch to debug...
The incorrect name with ';' could be related to #986

**Comment by ConiKost** [comment]
Sorry, I should be more clear.
The log is create @ /var/lib/owncloud/owncloud.log. When I create a new contact from Windows Phone, this is beeing logged in owncloud.log. See my output.

When I delete on ownCloud this new contact, Windows Phone does sync that one specific and a debug log similar is written.

But there is nothing logged, when I start the sync normally with ownCloud.

So yes, the directory is writable and owncloud.log gets written..

Create contact on WP
{"reqId":"5DNjvK54dq\/r34u840da","remoteAddr":"1.2.3.4","app":"contacts","message":"OCA\\Contacts\\Backend\\Database::getContact, Not found, id: 040000008200E00074C5B7101A82E008000000008277666B83641B4E99F9ADD83AB2ADFA10000000F21CB0E309EF894DA722F0EC92C50D27.vcf","level":0,"time":"2015-07-23T09:06:12+00:00","method":"PUT","url":"\/remote.php\/carddav\/addressbooks\/xxx\/kontakte\/040000008200E00074C5B7101A82E008000000008277666B83641B4E99F9ADD83AB2ADFA10000000F21CB0E309EF894DA722F0EC92C50D27.vcf"}
{"reqId":"5DNjvK54dq\/r34u840da","remoteAddr":"1.2.3.4","app":"contacts","message":"OCA\\Contacts\\Backend\\Database::getContact, Not found, id: 040000008200E00074C5B7101A82E008000000008277666B83641B4E99F9ADD83AB2ADFA10000000F21CB0E309EF894DA722F0EC92C50D27.vcf","level":0,"time":"2015-07-23T09:06:12+00:00","method":"PUT","url":"\/remote.php\/carddav\/addressbooks\/xxx\/kontakte\/040000008200E00074C5B7101A82E008000000008277666B83641B4E99F9ADD83AB2ADFA10000000F21CB0E309EF894DA722F0EC92C50D27.vcf"}
{"reqId":"5DNjvK54dq\/r34u840da","remoteAddr":"1.2.3.4","app":"contacts","message":"OCA\\Contacts\\Backend\\Database::getContact, Not found, id: 040000008200E00074C5B7101A82E008000000008277666B83641B4E99F9ADD83AB2ADFA10000000F21CB0E309EF894DA722F0EC92C50D27.vcf","level":0,"time":"2015-07-23T09:06:12+00:00","method":"PUT","url":"\/remote.php\/carddav\/addressbooks\/xxx\/kontakte\/040000008200E00074C5B7101A82E008000000008277666B83641B4E99F9ADD83AB2ADFA10000000F21CB0E309EF894DA722F0EC92C50D27.vcf"}
{"reqId":"5DNjvK54dq\/r34u840da","remoteAddr":"1.2.3.4","app":"contacts","message":"OCA\\Contacts\\Hooks::contactAdded id: 171","level":0,"time":"2015-07-23T09:06:12+00:00","method":"PUT","url":"\/remote.php\/carddav\/addressbooks\/xxx\/kontakte\/040000008200E00074C5B7101A82E008000000008277666B83641B4E99F9ADD83AB2ADFA10000000F21CB0E309EF894DA722F0EC92C50D27.vcf"}
{"reqId":"5DNjvK54dq\/r34u840da","remoteAddr":"1.2.3.4","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 171\n)\n","level":0,"time":"2015-07-23T09:06:12+00:00","method":"PUT","url":"\/remote.php\/carddav\/addressbooks\/xxx\/kontakte\/040000008200E00074C5B7101A82E008000000008277666B83641B4E99F9ADD83AB2ADFA10000000F21CB0E309EF894DA722F0EC92C50D27.vcf"}
{"reqId":"5DNjvK54dq\/r34u840da","remoteAddr":"1.2.3.4","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 171\n)\n","level":0,"time":"2015-07-23T09:06:12+00:00","method":"PUT","url":"\/remote.php\/carddav\/addressbooks\/xxx\/kontakte\/040000008200E00074C5B7101A82E008000000008277666B83641B4E99F9ADD83AB2ADFA10000000F21CB0E309EF894DA722F0EC92C50D27.vcf"}


Delete contact on ownCloud:
{"reqId":"VDjDtRWPCUNRGY3C6+Cw","remoteAddr":"1.2.3.4","app":"files_locking","message":"INFO: Read lock requested for \/var\/lib\/owncloud\/xxx\/avatar.png","level":0,"time":"2015-07-23T09:07:05+00:00","method":"GET","url":"\/index.php\/avatar\/xxx\/32?requesttoken=B7m4PAwbv%2F%2B1ex6MR5JIaQTXRBH7KF"}
{"reqId":"VDjDtRWPCUNRGY3C6+Cw","remoteAddr":"1.2.3.4","app":"files_locking","message":"PASS: Acquired read lock for \/var\/lib\/owncloud\/xxx\/avatar.png","level":0,"time":"2015-07-23T09:07:05+00:00","method":"GET","url":"\/index.php\/avatar\/xxx\/32?requesttoken=B7m4PAwbv%2F%2B1ex6MR5JIaQTXRBH7KF"}
{"reqId":"VDjDtRWPCUNRGY3C6+Cw","remoteAddr":"1.2.3.4","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/var\/lib\/owncloud\/xxx\/avatar.png","level":0,"time":"2015-07-23T09:07:05+00:00","method":"GET","url":"\/index.php\/avatar\/xxx\/32?requesttoken=B7m4PAwbv%2F%2B1ex6MR5JIaQTXRBH7KF"}
{"reqId":"VDjDtRWPCUNRGY3C6+Cw","remoteAddr":"1.2.3.4","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/var\/lib\/owncloud\/xxx\/avatar.png","level":0,"time":"2015-07-23T09:07:05+00:00","method":"GET","url":"\/index.php\/avatar\/xxx\/32?requesttoken=B7m4PAwbv%2F%2B1ex6MR5JIaQTXRBH7KF"}
{"reqId":"\/5t\/fQo9KsSba6XNLTgN","remoteAddr":"1.2.3.4","app":"files_locking","message":"INFO: Read lock requested for \/var\/lib\/owncloud\/xxx\/avatar.png","level":0,"time":"2015-07-23T09:07:05+00:00","method":"GET","url":"\/index.php\/avatar\/xxx\/128?requesttoken=B7m4PAwbv%2F%2B1ex6MR5JIaQTXRBH7KF"}
{"reqId":"\/5t\/fQo9KsSba6XNLTgN","remoteAddr":"1.2.3.4","app":"files_locking","message":"PASS: Acquired read lock for \/var\/lib\/owncloud\/xxx\/avatar.png","level":0,"time":"2015-07-23T09:07:05+00:00","method":"GET","url":"\/index.php\/avatar\/xxx\/128?requesttoken=B7m4PAwbv%2F%2B1ex6MR5JIaQTXRBH7KF"}
{"reqId":"\/5t\/fQo9KsSba6XNLTgN","remoteAddr":"1.2.3.4","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/var\/lib\/owncloud\/xxx\/avatar.png","level":0,"time":"2015-07-23T09:07:05+00:00","method":"GET","url":"\/index.php\/avatar\/xxx\/128?requesttoken=B7m4PAwbv%2F%2B1ex6MR5JIaQTXRBH7KF"}
{"reqId":"\/5t\/fQo9KsSba6XNLTgN","remoteAddr":"1.2.3.4","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/var\/lib\/owncloud\/xxx\/avatar.png","level":0,"time":"2015-07-23T09:07:05+00:00","method":"GET","url":"\/index.php\/avatar\/xxx\/128?requesttoken=B7m4PAwbv%2F%2B1ex6MR5JIaQTXRBH7KF"}
{"reqId":"zjD+1jJwJJzHg1pi0KG0","remoteAddr":"1.2.3.4","app":"files_locking","message":"INFO: Read lock requested for \/var\/lib\/owncloud\/xxx\/avatar.png","level":0,"time":"2015-07-23T09:07:05+00:00","method":"GET","url":"\/index.php\/avatar\/xxx\/128?requesttoken=B7m4PAwbv%2F%2B1ex6MR5JIaQTXRBH7KF"}
{"reqId":"zjD+1jJwJJzHg1pi0KG0","remoteAddr":"1.2.3.4","app":"files_locking","message":"PASS: Acquired read lock for \/var\/lib\/owncloud\/xxx\/avatar.png","level":0,"time":"2015-07-23T09:07:05+00:00","method":"GET","url":"\/index.php\/avatar\/xxx\/128?requesttoken=B7m4PAwbv%2F%2B1ex6MR5JIaQTXRBH7KF"}
{"reqId":"zjD+1jJwJJzHg1pi0KG0","remoteAddr":"1.2.3.4","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/var\/lib\/owncloud\/xxx\/avatar.png","level":0,"time":"2015-07-23T09:07:05+00:00","method":"GET","url":"\/index.php\/avatar\/xxx\/128?requesttoken=B7m4PAwbv%2F%2B1ex6MR5JIaQTXRBH7KF"}
{"reqId":"zjD+1jJwJJzHg1pi0KG0","remoteAddr":"1.2.3.4","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/var\/lib\/owncloud\/xxx\/avatar.png","level":0,"time":"2015-07-23T09:07:05+00:00","method":"GET","url":"\/index.php\/avatar\/xxx\/128?requesttoken=B7m4PAwbv%2F%2B1ex6MR5JIaQTXRBH7KF"}
{"reqId":"GqD5I5jTV5TklDiD4Y0y","remoteAddr":"1.2.3.4","app":"core","message":"OC\\Tags::getFavorites, exception: Could not find category \"_$!<Favorite>!$_\"","level":0,"time":"2015-07-23T09:07:05+00:00","method":"GET","url":"\/index.php\/apps\/contacts\/groups\/"}
{"reqId":"\/c4oBp+x5aSbK4b2\/qw+","remoteAddr":"1.2.3.4","app":"contacts","message":"OCA\\Contacts\\Hooks::contactDeletion id: 171","level":0,"time":"2015-07-23T09:07:22+00:00","method":"DELETE","url":"\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/171"}
{"reqId":"\/c4oBp+x5aSbK4b2\/qw+","remoteAddr":"1.2.3.4","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 171\n)\n","level":0,"time":"2015-07-23T09:07:22+00:00","method":"DELETE","url":"\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/171"}
{"reqId":"\/c4oBp+x5aSbK4b2\/qw+","remoteAddr":"1.2.3.4","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 171\n)\n","level":0,"time":"2015-07-23T09:07:22+00:00","method":"DELETE","url":"\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/171"}

**Comment by ConiKost** [comment]
> The incorrect name with ';' could be related to #986
Thanks! That fixed the ";" for me.

**Comment by gvde** [comment]
Those four PROPFINDs from the web server logs are the only requests done by the client?
You can try those PROPFINDs manually using curl, e.g.
````
curl -X PROPFIND -u xxx https://cloud.xxx.de/remote.php/carddav/principals/xxx/
curl -X PROPFIND -u xxx https://cloud.xxx.de/remote.php/carddav/addressbooks/xxx/
````
The latter should list all the address books for your user in a 207 multi-status.

**Comment by ConiKost** [comment]
Correct. The 4 logs are from my Windows Phone.

Curl replies on both comands:
curl: (52) Empty reply from server

Thats strange?

**Comment by ConiKost** [comment]
My guess is, the problem are the *.vcf files. I've now exported one entry, which is not being synced and a new entry, created by Owncloud.

The old one, if again imported, is still not beeing synced. The new entry is beeing synced. (I've replaced personal data)

NOT SYNCED:
BEGIN:VCARD
VERSION:3.0
PRODID:-//ownCloud//NONSGML Contacts 0.4.0.0//EN
FN:Firstname Lastname
N;SORT-AS=Lastname,Firstname:Lastname;Firstname;;;
ORG:Company;
BDAY:1970-01-01
X-ABLABEL;UNKNOWN=ITEM1:_$!<HomePage>!$_
UID:urn:uuid:5f4bad60-3bef-41d3-82df-207b4305ac5a
REV:2015-07-23T09:46:32+00:00
CATEGORIES:Users
EMAIL;TYPE=HOME:user@mail.com
TEL;TYPE=HOME:+491234567890
TEL;TYPE=HOME:+491234567891
TEL;TYPE=CELL:+491234567892
TEL;TYPE=CELL:+491234567893
ADR;TYPE=HOME:;;Street 1;Location;State;Postcode;Country
ADR;TYPE=HOME:;;Street 2;Location;State;Postcode;Country
URL;TYPE=WORK:https://www.domain.tld/
END:VCARD

SYNCED:
BEGIN:VCARD
VERSION:3.0
PRODID:-//ownCloud//NONSGML Contacts 0.4.0.0//EN
N:Firstname;Lastname;;;
UID:4ada341f-6c52-4441-b0b6-cb9b9ab4d1b5
REV:2015-07-23T09:49:49+00:00
FN:Firstname Lastname
ORG:Company
EMAIL;TYPE=HOME:user@mail.com
TEL;TYPE=HOME:+491234567890
TEL;TYPE=HOME:+491234567891
TEL;TYPE=CELL:+491234567892
TEL;TYPE=CELL:+491234567893
ADR;TYPE=HOME:;;Street 1;Location;State;Postcode;Country
ADR;TYPE=HOME:;;Street 2;Location;State;Postcode;Country
CATEGORIES:Users
END:VCARD

**Comment by gvde** [comment]
> Curl replies on both comands:
> curl: (52) Empty reply from server
>
> Thats strange?

That's very strange. That can't be. Does curl ask you for your password? You have replaced the xxx the correct user name?

Can you check the web server log for the corresponding logs for those curl calls?

**Comment by ConiKost** [comment]
Sorry. You are right. I've made a typo, which I didn't see.. Here is the output:

curl -k -X PROPFIND -u xxx https://cloud.xxx.de/remote.php/carddav/principals/xxx
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:card="urn:ietf:params:xml:ns:carddav"><d:response><d:href>/remote.php/carddav/principals/xxx/</d:href><d:propstat><d:prop><d:getlastmodified>Thu, 23 Jul 2015 10:39:41 GMT</d:getlastmodified><d:resourcetype><d:collection/><d:principal/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/carddav/principals/xxx/calendar-proxy-read/</d:href><d:propstat><d:prop><d:resourcetype><d:principal/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/carddav/principals/xxx/calendar-proxy-write/</d:href><d:propstat><d:prop><d:resourcetype><d:principal/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>

curl -k -X PROPFIND -u xxx https://cloud.xxx.de/remote.php/carddav/addressbooks/xxx/kontakte
I am getting a very long list. There are a lot of *.vcf

This is only a small part of it, as it's very long:
<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:card="urn:ietf:params:xml:ns:carddav"><d:response><d:href>/remote.php/carddav/addressbooks/xxx/kontakte/</d:href><d:propstat><d:prop><d:getlastmodified>Thu, 23 Jul 2015 10:29:17 GMT</d:getlastmodified><d:resourcetype><d:collection/><card:addressbook/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/carddav/addressbooks/xxx/kontakte/urn%253Auuid%253Acd3e73c6-bc3f-4cae-8b7d-45d80e2c619d.vcf</d:href><d:propstat><d:prop><d:getlastmodified>Wed, 22 Jul 2015 17:57:50 GMT</d:getlastmodified><d:getcontentlength>694</d:getcontentlength><d:resourcetype/><d:getetag>"49294512f1c20e5256d7cd746ae5fbe1"</d:getetag><d:getcontenttype>text/vcard; charset=utf-8</d:getcontenttype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/carddav/addressbooks/xxx/kontakte/urn%253Auuid%253A815e1af2-0996-41f3-bd5d-c5de1b38633b.vcf</d:href><d:propstat><d:prop><d:getlastmodified>Wed, 22 Jul 2015 17:57:50 GMT</d:getlastmodified>

**Comment by gvde** [comment]
Now that's better. The second curl is without the "kontakte" at the end. At least that was the last URL from your web server logs you have posted before...
````
curl -k -X PROPFIND -u xxx https://cloud.xxx.de/remote.php/carddav/addressbooks/xxx/
````
should list all the address books.

**Comment by ConiKost** [comment]
Eh, yeah. "kontakte" is the name of my addressbook itself.

curl -k -X PROPFIND -u xxx https://cloud.xxx.de/remote.php/carddav/addressbooks/xxx/
'''
<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:card="urn:ietf:params:xml:ns:carddav"><d:response><d:href>/remote.php/carddav/addressbooks/xxx/</d:href><d:propstat><d:prop><d:resourcetype><d:collection/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/carddav/addressbooks/xxx/kontakte/</d:href><d:propstat><d:prop><d:getlastmodified>Thu, 23 Jul 2015 11:09:16 GMT</d:getlastmodified><d:resourcetype><d:collection/><card:addressbook/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
'''

**Comment by Garfonso** [comment]
I added the fix from #987 to my owncloud and contacts now do sync for me after altering contacts in all my addressbooks (which is the same as with the calendar fix => WP8.1 checks the ctag and sees that there are no changes to by synced, i.e. skips the addressbook).

I'm also pretty sure that WP uses multi-get, because there are no single GET request, but only a single REPORT request for each addressbook (or calendar) like here:

```
*** - xxx [23/Jul/2015:13:51:09 +0200] "PROPFIND /owncloud/remote.php/carddav/addressbooks/xxx/shared_shared_by_Lager/ HTTP/1.1" 207 3594 "-" "MSFT-WP/8.10.15148 (gzip)"
*** - xxx [23/Jul/2015:13:51:10 +0200] "REPORT /owncloud/remote.php/carddav/addressbooks/xxx/shared_shared_by_Lager/ HTTP/1.1" 207 2154 "-" "MSFT-WP/8.10.15148 (gzip)"
```

**Comment by gvde** [comment]
@Garfonso For shared addressbooks and clients using multi-get you'll need #987. The REPORT request contains the multi-get in an XML document sent as contents. The REPORT will return multiple cards with a single call.

@ConiKost The multi status for the curl call is "HTTP/1.1 200 OK". That's all O.K. So I suppose you have to do that "fix" as mentioned by Garfonso. Sounds reasonable that the client doesn't retrieve the cards if it thinks the address book hasn't changed...

**Comment by ConiKost** [comment]
I've already #987 patched into my ownCloud. How do I alter all contacts?
I've tried to increase ctag in oc_contacts_addressbooks, but this did not help.
I've also tried to increase lastmodified in oc_contacts_cards, but this did not help.

What do I have to modify exactly? (I didn't refresh ctag with calendar, but recreated the account on WP, but with contacts, this did not help)

**Comment by Garfonso** [comment]
For me it was sufficient to alter *one* contact (in every addressbook that I sync) using the owncloud webinterface.
I did that addressbook by addressbook and in between told WP8.1 to sync the account and could see how the contacts of each addressbooks were downloaded.

**Comment by ConiKost** [comment]
Well, that is not working for me :/
If I alter existing contacts, they are still not synced. When I create a new account, that one is being synced..

**Comment by ConiKost** [comment]
Ok, I see the problem. I can now reproduce.

All existing contacts have:
UID:urn:uuid:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

All new contacts have:
UID:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

When I export all contacts, search and replace UID:urn:uuid with UID, it works. All contacts are being synced with WP.

When I revert this change and import all contacts again, WP looses on the next sync again all contacts.

**Comment by Bugahans** [comment]
I have exactly the same problem.
I added both fixes. 

new conctacts are synced in both directions but the old ones are only listed in the web gui.
I guess I have to fix these uid manually:(

**Comment by Garfonso** [comment]
Hm. Not sure where you got the contacts with this UID from... did you import contacts from somewhere? I have no contacts with such an UID in my database. 
Even if you alter such a contact and do a sync with WP8.1, do you see a "REPORT" request in the access log of the server, i.e. does WP8.1 try to download the contact at all? 

And you see nothing in the owncloud log during a sync, if such a contact was altered?

**Comment by ConiKost** [comment]
Yeah. Most Imports are done from eM Client. So I guess, that one have used such UID-string.

**Comment by Bugahans** [comment]
I am looking into my database and see the following differences:
table oc_contacts_cards column uri
old=ab797ee3-7595-4136-a8df-af068aaa4552@192.168.178.100.vcf | not working
new=040000008200E00074C5B7101A82E008000000009F07AD589751F44E8468E41304EFEBF410000000AF805AAAC3847D47A4E996039EDA54AF.vcf | working

any ideas?

**Comment by Bugahans** [comment]
Update:
I deleted the @192.168.178.100 directly in the db (oc_contacts_cards and oc_contacts_cards_properties)
=> no change
when I also edit for example the name of the contact it is displayed!!

So I have to remove the ip from the uid and "touch" each entry to get all my contacts back...

**Comment by Bugahans** [comment]
I fixed the issue for my local problem. perhaps it helps others:
I rund the following 2 sql Statements to remove the @IP from my contact ids.
UPDATE oc_contacts_cards SET uri = REPLACE(uri,"@192.168.178.100",""), carddata = REPLACE(carddata,"@192.168.178.100","")
WHERE uri like "%@192.168.178.100%"

UPDATE oc_contacts_cards_properties SET value = REPLACE(value,"@192.168.178.100","")
WHERE value like "%@192.168.178.100%"

than I disabled the contacts on my phone and reenabled them, so that the old contacts are also fetched without updating them manually.

that's it. now I have also my "old" contacts back on my phone.

**Comment by Garfonso** [comment]
Strange. I just checked: I have quite some contacts with @hostname in the UID and they work quite fine...

**Comment by gvde** [comment]
Maybe it depends on whether it's the freetext form or an URI, e.g. UID:urn:uuid:f81d4fae-7dec-11d0-a765-00a0c91e6bf6
If it's the latter it must be a properly formatted UUID and must not contain an hostname.
If it's free text (i.e. it does not start with urn:uuid:) it can contain anything...

**Comment by Monstereye** [comment]
I had the same issue that with owncloud 8.1 old contacts did not sync anymore with windows phone 8.1. 
I patched also #987 into my owncloud but that did not solve the issue. 
Then I followed the hint to remove domain name after UID.
I exported all contacs to *.vcf file. Removed the @domainname.de from  all UID.
Then I deleted all contacts in owncloud and imported the recently changed *.vcf file.
That finally solved this problem.
Thanks to Bugahans!

Regards

**Comment by elvenbone** [comment]
I had the same problem and could fix it the same way: removing the @-sign from the UIDs is all that is necessary (my UIDs just start with UID:, not with UID:urn:uuid:

And now the interesting part:
I can confirm this is likely not a bug in Windows Phone!
I have exactly the same problem on my Kubuntu system in the KDE application "Kontact":
Contacts with numbers-only UIDs show fine, contacts with @hostname in it do not show up.
No error appears, but I haven't searched through the system logs and don't know where to look.

So either KDE and WP8.1 have the same bug (which I find unlikely) or it is a bug on the owncloud-side, right?
Could it be the @ needs to be parsed in some special way?
Sorry I cannot help directly with fixing the problem, I don't have enough time to learn PHP right now...

best regards
elvenbone

**Comment by cheinig** [comment]
Same problem for me using Windows 10 and the carddav sync with icloud workaround. Not all of my contacts were synced to my "People" app and the reason was the additional @hostname in the UID value. 
The real problem is not the @hostname in the UID value of the card, but the URI used by owncloud. Owncloud sets the URI to this contact card equal to the UID of this contact and this failed. If i remove all @hostname values from URI column in the database, the sync works fine.

**Comment by bnavigator** [comment]
Same here with KDE Adressbook /Akonadi CardDAV Ressource. I had filed a bug with KDE https://bugs.kde.org/show_bug.cgi?id=351652

So basically old ownCloud Servers created VCards with UIDs ending with "@hostname".
This was changed here: https://github.com/owncloud/contacts/commit/d363f85455feb957ec6833afa049c7ea7e890a14

The @ sign in the vcard is not encoded properly in the filename fitting to the UID property. Not all clients are okay with DAV resource filenames different to the UID property within the card, I guess.

The workaround is to fix the UID either by manually editing the database entries or by exporting the whole addressbook to file, edit all UID properties in the file and import back to a blank addressbook.

Nevertheless the Server should fix the UID handling of old entries created by old ownCloud versions.

**Comment by gvde** [comment]
I don't see anything wrong with those URLs. I did a PROPFIND and it does in fact return a double encoded @ in the URL. Still the URL works fine and I can retrieve the card using that exact URL. I can see in the logs that other clients handle this correctly.
So this is a windows phone problem. Probably they decode the double encoded strings twice (which is incorrect) and then interpret it as @ sign in the URL (i.e. the part after that is the hostname and the part before is the user name to use..)
@bnavigator IMHO comment 5 in the KDE bug is incorrect. The URI is in deed double encoded but it correct. It doesn't look nice but it works. It would be interesting to see what URL they create to retrieve the card from that URI in the REPORT.

**Comment by goestreicher** [comment]
Hey,

I'm the KDE DAV resource maintainer. Regarding the KDE issue you're right in that the resource transforms the %2540 into %40. I have a fix pending for that, thanks for pointing it :)

Now another thing is odd. Here is a REPORT query as sent by the resource to retrieve this element:

```xml
<addressbook-multiget xmlns="urn:ietf:params:xml:ns:carddav">
 <prop xmlns="DAV:">
  <getetag xmlns="DAV:"/>
  <address-data xmlns="urn:ietf:params:xml:ns:carddav">
   <allprop xmlns="DAV:"/>
  </address-data>
 </prop>
 <href xmlns="DAV:">/remote.php/carddav/addressbooks/greg/contacts/20140721T192733.4cc4ba55ef%2540url.of.my.server.de.vcf</href>
</addressbook-multiget>
```

So far, so good the %2540 is kept as-is with the incoming fix, and the resource gets some content back. Now here's the reply from ownCloud:

```xml
<d:multistatus xmlns:d="DAV:">
 <d:response xmlns:d="DAV:">
  <d:href xmlns:d="DAV:">/remote.php/carddav/addressbooks/greg/contacts/20140721T192733.4cc4ba55ef@url.of.my.server.de.vcf</d:href>
  <d:propstat xmlns:d="DAV:">
   <d:prop xmlns:d="DAV:">
    <d:getetag xmlns:d="DAV:">"20c2aadc593945526596071e8f3e2093"</d:getetag>
    <card:address-data xmlns:card="urn:ietf:params:xml:ns:carddav">BEGIN:VCARD&#xd;
VERSION:3.0&#xd;
PRODID:-//ownCloud//NONSGML Contacts 0.3//EN&#xd;
FN:Some Name&#xd;
N:Name;Some;;;&#xd;
EMAIL;TYPE=INTERNET:foo@bar.com&#xd;
TEL;TYPE=HOME:+1234553&#xd;
UID:20140721T192733.4cc4ba55ef@url.of.my.server.de&#xd;
REV:2015-08-31T20:08:01+00:00&#xd;
END:VCARD&#xd;
    </card:address-data>
   </d:prop>
   <d:status xmlns:d="DAV:">HTTP/1.1 200 OK</d:status>
  </d:propstat>
 </d:response>
</d:multistatus>
```

Now, not so good :| In the <href/> tag the %2540 has been decoded to '@', a transformation that prevents the resource from associating this data with the item it requested.

Cheers,
Grégory

**Comment by gvde** [comment]
Can you try to undo commit 3ee20ca1b62bff67fcf71adfcbef1affa8007dc8?
I.e. remove the urlencode and urldecode calls in line 192 and 209?
Then URIs should contain the '@' again which is IMHO consistent. Of course, it may need another encode somewhere else where the URI is put into a URL...
